# -*- coding: utf-8 -*-
"""hypertensionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNjJSpcug4_yrARvm4GI0qruSpPGvvln
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from xgboost import plot_importance
import shap

"""# **1. Research Objective**

Develop and evaluate machine learning models that can predict the likelihood of hypertension based ondemographic, lifestyle, and clinical factors.
"""

df_hypertension = pd.read_csv('/content/drive/MyDrive/seyi/datasetss/hypertention.csv')

"""# **2. Research Key Questions**

*   Which factors contribute most to hypertension risk.
*   Which ML model performs best for prediction?
*   Can lifestyle variables alone predict hypertension effectively?
*   How early can we detect risk before clinical diagnosis?

"""

df_hypertension.head()

"""# **3. Dataset Understanding**

Your dataset contains the following variables:
- Age
- Salt Intake
- Stress Score
- BP History
- Sleep Duration
- BMI
- Medication
- Family History
- Exercise Level
- Smoking Status
- Has Hypertension
"""

# How many rows
df_hypertension.shape[0]

# How many columns
df_hypertension.shape[1]

# How many columns
df_hypertension.head()

# identify the prediction target
# To check the balance state of the target variable.
df_hypertension["Has_Hypertension"].value_counts()

#check columns
df_hypertension.dtypes

# categorical features
df_hypertension.select_dtypes(include="object").columns

# numerical features
df_hypertension.describe()

#missing values
df_hypertension.isnull().sum()

"""# **4. Methodology**

**Step 1: Data Preprocessing**

- Handle missing values
- Encode categorical variables (e.g. smoking, gender)
- Normalize/standardize numerical features.
- Remove outliers (optional but valiable)
"""

# fill the missing values with mode
df_hypertension["Medication"].fillna(df_hypertension["Medication"].mode()[0], inplace=True)

df_hypertension.isnull().sum()

#drop duplicatess
# fill the missing values with mode
df_hypertension.duplicated().sum()

# outliers
df_hypertension.boxplot(figsize=(12,6))

df_hypertension.hist(figsize=(12,10))

#copy the dataset
dfh = df_hypertension.copy()

dfh.head()

dfh["BP_History"].value_counts()

sns.countplot(dfh["BP_History"])

dfh["Medication"].value_counts()

sns.countplot(dfh["Medication"])

dfh["Exercise_Level"].value_counts()

sns.countplot(dfh["Exercise_Level"])

dfh['Smoking_Status'].value_counts()

sns.countplot(dfh["Smoking_Status"])

#encoding
cat_cols = ['BP_History', 'Medication', 'Family_History', 'Exercise_Level', 'Smoking_Status', 'Has_Hypertension']
num_cols = ['Age', 'Salt_Intake', 'Stress_Score', 'Sleep_Duration', 'BMI']

le = LabelEncoder()

for x in cat_cols:
  dfh[x] = le.fit_transform(dfh[x])

dfh.head()

"""**Step 2: Exploratory Data Analysis (EDA)**

- Correlation heatmap
- Distribution of hypertention vs non-hypertension
- Feature relationship (e.g. BMI vs BP)
"""

for y in num_cols:
  sns.boxplot(x="Has_Hypertension", y=y, data=dfh)
  plt.show()

df_corr = dfh.corr()

df_corr

#heatmap
plt.figure(figsize=(10,8))
sns.heatmap(df_corr, annot=True)

#Distribution of hypertention vs non-hypertension
plt.figure(figsize=(8,6))
sns.countplot(data=dfh, x="Has_Hypertension")
plt.show()

#Bivariate Analysis
plt.figure(figsize=(10,6))
sns.countplot(data=df_hypertension, x="Medication", hue="Has_Hypertension")
plt.show()

#Bivariate Analysis
plt.figure(figsize=(10,6))
sns.countplot(data=df_hypertension, x="Smoking_Status", hue="Has_Hypertension")
plt.show()

#Bivariate Analysis
plt.figure(figsize=(10,6))
sns.boxplot(data=df_hypertension, y="Age", x="Has_Hypertension")
plt.show()

#Bivariate Analysis
plt.figure(figsize=(10,6))
sns.boxplot(data=df_hypertension, y="Salt_Intake", x="Has_Hypertension")
plt.show()

"""**Step 3: Model Selection**  
Train and compare multiple models:
- Logistics Regression
- Decision Tree
- Random Forest
- Gradient Boosting (XGBoost/LightGBM)
- Support Vector Machine (optional)
"""

# split the features
X = dfh.drop("Has_Hypertension", axis=1)
y = dfh["Has_Hypertension"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#scaling the data
scaler = StandardScaler()
X_train_scales = scaler.fit_transform(X_train)
X_test_scales = scaler.transform(X_test)

#trainin

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "XGBoost": XGBClassifier(eval_metric = 'logloss'),
    "LightGBM": LGBMClassifier(probability = True)
}

results = {}

for name, model in models.items():
  model.fit(X_train_scales, y_train)

  y_pred = model.predict(X_test_scales)

  accuracy = accuracy_score(y_test, y_pred)

  results[name] = accuracy
  print(f"{name} Accuracy: {accuracy:.4f}")

"""**Step 4: Model Evaluation**  
Possible methods:
- Accuracy
- Precision /Recall
- F1 Score
- ROC-AUC Curve
"""

print(classification_report(y_test, y_pred))

"""**Step 5: Feature Importance**  
Identify key drivers of hypertension:
- BMI?
- Stress?
- Salt intake?

Use:
- Feature importance
- SHAP values
"""

plot_importance(models["XGBoost"], importance_type="gain", max_num_features=5)
plt.title("XGBoost Feature Importance")
plt.show()

feature_names = X.columns.tolist()

mapper = {f'f{i}': name for i, name in enumerate(feature_names)}

mapper_impotance = {mapper[k]: v for k, v in models["XGBoost"].get_booster().get_score(importance_type="gain").items()}

import xgboost as xgb
xgb.plot_importance(mapper_impotance, importance_type="gain")
#shap_values = shap.TreeExplainer(models["XGBoost"]).shap_values

X_test_df  = pd.DataFrame(X_test_scales, columns=X.columns)

explainer = shap.TreeExplainer(models["XGBoost"])
shap_values = explainer.shap_values(X_test_df)

shap.summary_plot(shap_values, X_test_df)

"""# 5. Expected Findings (Typical Insights)
You may discover:
- High BMI + high stress = strongest predictors. (Partial Match)
- Sleep deprivation significantly increases risk. (Confirmed)
- Lifestyle factors rival gentic factors. (Smoking, Stress, and Salt) - (Confirmed)
- Some "healthy-looking" individuals still fall into risk clusters. (confirmed)
"""

